version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8008:8008" # Map container's port 8008 to host's port 8008
    environment:
      - FLASK_APP=app/app.py
    networks:
      - webapp-network

networks:
  webapp-network:
    driver: bridge
